// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_CB_MaterialBundle)
QT_DECLARE_EXTERN_RESOURCE(qmake_ComponentBundles_MaterialBundle)
QT_DECLARE_EXTERN_RESOURCE(CB_MaterialBundle_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_ComponentBundles_MaterialBundle)

class CB_MaterialBundlePlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    CB_MaterialBundlePlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_ComponentBundles_MaterialBundle)
QT_KEEP_RESOURCE(qmlcache_CB_MaterialBundle)
QT_KEEP_RESOURCE(qmake_ComponentBundles_MaterialBundle)
QT_KEEP_RESOURCE(CB_MaterialBundle_raw_qml_0)
    }
};



#include "CB_MaterialBundleplugin_CB_MaterialBundlePlugin.moc"
